js_notification_DOM
mate-academy/js_notification_DOM pull request #643
Opened 2023-02-09 17:16 UTC by mykolahuryn

[DEMO LINK](https://mykolahuryn.github.io/js_notification_DOM/)

2023-02-10 15:46 UTC, slavanosatskyi requested changes
Nice, though there are a couple of changes needed

2023-02-10 15:46 UTC, slavanosatskyi commented on src/scripts/main.js
> +  const p = document.createElement('p');
Would be better to provide more meaningful names here - notification, header, content

2023-02-10 15:46 UTC, slavanosatskyi commented on src/scripts/main.js
> +  div.style.right = posRight + 'px';
as an option you can use here string templates

2023-02-23 14:07 UTC, witflash approved these changes
Much better!
Well done 👍🏻

2024-10-25 09:22 UTC, closed without merging